### ISSUE TITLE
bedroom-sketch.svg needs to have inkscape cruft removed

### ISSUE THREAD

**Issue by robinwhittleton** [maticstric/agatha-christie_poirot-investigates#2]
Basically we just want the path and title, and not much else. An example would be this image from Tristram Shandy: https://raw.githubusercontent.com/standardebooks/laurence-sterne_the-life-and-opinions-of-tristram-shandy-gentleman/master/src/epub/images/illustration-1.svg

**Comment by robinwhittleton** [comment]
It’s also nice to have a PNG from the original source scans in the ./images folder if we want to change it later, but that’s not necessary :)

**Comment by acabal** [comment]
Please do include the original PNG in ./images/. Thanks!

**Comment by maticstric** [comment]
Done and done!
