### ISSUE TITLE
“service” is emphasised in the scans

### ISSUE THREAD

**Issue by robinwhittleton** [maticstric/agatha-christie_poirot-investigates#6]
https://github.com/maticstric/agatha-christie_poirot-investigates/blob/28598956034fa303a81bc0faba8827270e7e4431/src/epub/text/jewel-robbery-at-the-grand-metropolitan.xhtml#L173

https://archive.org/details/in.ernet.dli.2015.148803/page/n121/mode/1up/search/%22I+demanded+impatiently%22

**Comment by maticstric** [comment]
I remember looking at that word and thinking, "It's French but it's in Merriam-Webster so I'll romanize it". For some reason never thought that it could just be emphasized...
